# Generated by Django 2.0.4 on 2018-11-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('address', models.CharField(max_length=1000)),
                ('status', models.BooleanField(default=False)),
                ('supplyrequest', models.CharField(default='Nothing!', max_length=5000)),
            ],
        ),
    ]
