# Generated by Django 2.0.4 on 2018-11-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='floodpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localx', models.FloatField()),
                ('localy', models.FloatField()),
            ],
        ),
    ]
