# Generated by Django 2.0.4 on 2018-11-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('locationx', models.FloatField()),
                ('locationy', models.FloatField()),
            ],
        ),
    ]
