# Generated by Django 2.0.4 on 2018-11-03 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='locationx',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='locationy',
            new_name='y',
        ),
    ]
