# Generated by Django 2.0.4 on 2018-11-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181104_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='supplyrequest',
            field=models.CharField(default='Nothing!', max_length=5000),
        ),
    ]
