# Generated by Django 2.0.4 on 2018-11-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181104_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='supplyrequest',
            field=models.IntegerField(default=0),
        ),
    ]
